// Copyright (c) 2026 Syd Polk
// SPDX-License-Identifier: BSD-3-Clause
//
// Blown leads: every game in which a team led by 11 or more runs and then gave
// the whole lead back — the trailing team drew level or went ahead.
//
// Method (two steps, Syd's):
//   1. Prefilter on the game logs for games where BOTH teams finished with 11+
//      runs. Lossless for this question, and it cuts 201,874 games to ~660.
//   2. Replay those games from the play table, tracking the score after every
//      play, and keep the ones where an 11+ run lead reached zero.
//
// Run (research default is Plex; override with DATABASE_URL):
//   tsx research/blown-11-run-leads/run.ts
//   DATABASE_URL=postgres://retrosheet:retrosheet@localhost:5432/retrosheet tsx research/blown-11-run-leads/run.ts
//
// Input : ../hof-sightings/attended-games.tsv  (only to mark games Syd was at)
// Output: 01-blown-leads.md, 02-near-misses.md, 03-data-quality.md (generated)
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { Pool } from "pg";
import {
  BLOWN_LEADS, NEAR_MISSES, POPULATION, RUN_DERIVATION_CHECK, PHANTOM_RUN_PLAYS,
  DROPPED_RUN_PLAYS, COVERAGE, COVERAGE_BY_DECADE,
} from "./queries.js";

// One row of BLOWN_LEADS. Scores are absolute (visitor/home); which side blew
// the lead is vis_blew/home_blew, and the rendering flips to leader-first.
interface BlownLead {
  game_id: string;
  game_date: string;
  visitor_team: string;
  home_team: string;
  visitor_name: string;
  home_name: string;
  vis_blew: boolean;
  home_blew: boolean;
  lead: number;
  peak_inning: number;
  peak_vis: number;
  peak_home: number;
  tie_inning: number;
  tie_vis: number;
  tie_home: number;
  visitor_score: number;
  home_score: number;
  innings: number;
  attendance: number | null;
  score_verified: boolean;
}

const DIR = dirname(fileURLToPath(import.meta.url));
const DB = process.env.DATABASE_URL ?? "postgres://retrosheet:retrosheet@plex:5432/retrosheet";
const MONTHS = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];
const fmt = (iso: string) => { const [y, m, d] = iso.split("-"); return `${MONTHS[+m - 1]} ${+d}, ${y}`; };
const pct = (n: number, d: number) => `${((100 * n) / d).toFixed(1)}%`;
const num = (n: number | null) => (n == null ? "—" : n.toLocaleString("en-US"));

// Games Syd was at. The attended log lives in the hof-sightings study; this is
// the second consumer, which is the case for promoting it to a mart table (see
// "Phase 9 — Attended-games table" in the project plan).
function attendedGameIds(): Set<string> {
  const ids = new Set<string>();
  const tsv = join(DIR, "..", "hof-sightings", "attended-games.tsv");
  for (const line of readFileSync(tsv, "utf8").split(/\r?\n/)) {
    const m = /boxesetc\/\d{4}\/B(\d\d)(\d\d)(\d)([A-Z]{3})(\d{4})\.htm/.exec(line);
    if (m) ids.add(`${m[4]}${m[5]}${m[1]}${m[2]}${m[3]}`);
  }
  return ids;
}

const tableExists = async (pool: Pool, qualified: string) =>
  (await pool.query(`SELECT to_regclass($1) IS NOT NULL AS ok`, [qualified])).rows[0].ok;
async function schemaVersion(pool: Pool) {
  if (!(await tableExists(pool, "retrosheet.schema_meta"))) return null;
  const r = await pool.query(`SELECT version FROM retrosheet.schema_meta LIMIT 1`);
  return r.rows[0]?.version ?? null;
}

async function main() {
  const attended = attendedGameIds();
  const pool = new Pool({ connectionString: DB });
  const ver = await schemaVersion(pool);
  const stamp = `<!-- generated by run.ts from ${DB.replace(/:[^:@/]*@/, ":***@")} `
    + `(schema ${ver === null ? "unversioned" : `v${ver}`}) on ${new Date().toISOString().slice(0, 10)} -->\n`;

  const games: BlownLead[] = (await pool.query(BLOWN_LEADS)).rows;
  const near = (await pool.query(NEAR_MISSES)).rows;
  console.log("replaying every game for the denominator (~40s)...");
  const pop = (await pool.query(POPULATION)).rows[0];
  const check = (await pool.query(RUN_DERIVATION_CHECK)).rows[0];
  const phantom = (await pool.query(PHANTOM_RUN_PLAYS)).rows[0];
  const dropped = (await pool.query(DROPPED_RUN_PLAYS)).rows[0];
  const cov = (await pool.query(COVERAGE)).rows[0];
  const covDecade = (await pool.query(COVERAGE_BY_DECADE)).rows;
  await pool.end();

  const blewIt = (r: BlownLead) => (r.vis_blew ? r.visitor_name : r.home_name);
  const cameBack = (r: BlownLead) => (r.vis_blew ? r.home_name : r.visitor_name);
  const survived = (r: BlownLead) =>
    r.vis_blew ? r.visitor_score > r.home_score : r.home_score > r.visitor_score;
  const box = (r: BlownLead) =>
    `https://www.retrosheet.org/boxesetc/${r.game_date.slice(0, 4)}/B`
    + `${r.game_id.slice(7, 11)}${r.game_id.slice(11)}${r.game_id.slice(0, 3)}${r.game_id.slice(3, 7)}.htm`;

  // --- 01-blown-leads.md -----------------------------------------------------
  const lost = games.filter((r) => !survived(r));
  let md = `${stamp}# Blown leads of 11 runs or more\n\n`;
  md += `**${games.length}** games in Retrosheet's play-by-play era (1900–2025) in which a team led `
     + `by 11 or more runs and then gave every run of it back. **${lost.length}** of them lost; `
     + `**${games.length - lost.length}** recovered to win anyway.\n\n`;
  md += `An 11-run lead has been held in **${num(+pop.led_by_11)}** of the `
     + `**${num(+pop.games)}** games with play-by-play, so it survives `
     + `${pct(+pop.led_by_11 - games.length, +pop.led_by_11)} of the time — the collapses below are `
     + `about one in ${Math.round(+pop.led_by_11 / games.length)}.\n\n`;
  md += "| Date | Game | Blew it | Peak lead | Level again | Final | Result |\n";
  md += "| --- | --- | --- | --- | --- | --- | --- |\n";
  for (const r of games) {
    const seen = attended.has(r.game_id) ? " ★" : "";
    const peak = r.vis_blew ? `${r.peak_vis}–${r.peak_home}` : `${r.peak_home}–${r.peak_vis}`;
    const tie = r.vis_blew ? `${r.tie_vis}–${r.tie_home}` : `${r.tie_home}–${r.tie_vis}`;
    const fin = r.vis_blew
      ? `${r.visitor_score}–${r.home_score}`
      : `${r.home_score}–${r.visitor_score}`;
    md += `| [${fmt(r.game_date)}](${box(r)})${seen} | ${r.visitor_team} @ ${r.home_team} `
       + `| ${blewIt(r)} | ${r.lead} (${peak}, ${ord(r.peak_inning)}) | ${tie} (${ord(r.tie_inning)}) `
       + `| ${fin}${r.innings > 9 ? ` / ${r.innings}` : ""} `
       + `| ${survived(r) ? "held on and won" : `lost to ${cameBack(r)}`} |\n`;
  }
  md += `\n_Scores are from the leading team's side. "Final / N" means the game went N innings._\n`;
  md += `_★ = Syd was there._\n`;
  md += `_Nicknames are the franchise's **current** one — the mart holds a single name per team id, `
     + `so 1925 and 1950 Cleveland read "Guardians"._\n`;

  const mine = games.filter((r) => attended.has(r.game_id));
  if (mine.length) {
    md += `\n## Games I was at\n\n`;
    for (const r of mine) {
      const winner = r.visitor_score > r.home_score ? r.visitor_name : r.home_name;
      const hi = Math.max(r.visitor_score, r.home_score);
      const lo = Math.min(r.visitor_score, r.home_score);
      md += `- **${fmt(r.game_date)}**, ${r.visitor_team} @ ${r.home_team} — ${blewIt(r)} led by `
         + `${r.lead} (${r.vis_blew ? `${r.peak_vis}–${r.peak_home}` : `${r.peak_home}–${r.peak_vis}`}, `
         + `${ord(r.peak_inning)}); ${cameBack(r)} drew level in the ${ord(r.tie_inning)}. `
         + `${winner} won ${hi}–${lo}. `
         + `Attendance ${r.attendance ? num(r.attendance) : "not recorded"}.\n`;
    }
  }
  writeFileSync(join(DIR, "01-blown-leads.md"), md);

  // --- 02-near-misses.md -----------------------------------------------------
  let nm = `${stamp}# One rung down: 10-run leads given up entirely\n\n`;
  nm += `**${near.length}** games where a 10-run lead — not 11 — was surrendered completely. `
     + `This table is also the study's safety net: a game whose reconstruction came up a run `
     + `short would land here rather than in the main list, so it is checked by hand.\n\n`;
  nm += "| Date | Game | Blew it | Peak lead | Final | Score verified |\n| --- | --- | --- | --- | --- | --- |\n";
  for (const r of near) {
    const seen = attended.has(r.game_id) ? " ★" : "";
    nm += `| ${fmt(r.game_date)}${seen} | ${r.visitor_team} @ ${r.home_team} `
       + `| ${r.vis_blew ? r.visitor_team : r.home_team} | ${r.lead} `
       + `| ${r.visitor_score}–${r.home_score} | ${r.score_verified ? "yes" : "**no**"} |\n`;
  }
  writeFileSync(join(DIR, "02-near-misses.md"), nm);

  // --- 03-data-quality.md ----------------------------------------------------
  const g = +check.games;
  let dq = `${stamp}# Data quality: why this study re-derives runs scored\n\n`;
  dq += `The question turns on the exact score after every play, so the run count per play has to `
     + `be right. The mart's \`play.runs_on_play\` is not, often enough to matter.\n\n`;
  dq += `## Final scores that match the game logs\n\n`;
  dq += "| Runs per play from | Games matching the official final | |\n| --- | --- | --- |\n";
  dq += `| \`play.runs_on_play\` (stored) | ${num(+check.stored_match)} of ${num(g)} | ${pct(+check.stored_match, g)} |\n`;
  dq += `| re-derived from the event string | ${num(+check.derived_match)} of ${num(g)} | ${pct(+check.derived_match, g)} |\n\n`;
  dq += `The derived count is the one this study uses. See \`RUNS\` in \`queries.ts\` for the rule.\n\n`;
  dq += `## Two bugs in the stored column\n\n`;
  dq += `**Phantom runs on force outs.** A run is credited on plays like \`64(1)/FO\` and \`5(2)/FO\` `
     + `that have no advance section at all — no runner is written as reaching home, so no run scored. `
     + `**${num(+phantom.plays)}** plays across **${num(+phantom.games)}** games.\n\n`;
  dq += `**Dropped runs on multi-run plays.** Fewer runs credited than there are advances to home in `
     + `the event, typically when a second run is marked \`(UR)\`: \`S9/L9M.3-H;2-H(UR);1-3\` scores two, `
     + `the mart records one. **${num(+dropped.plays)}** plays across **${num(+dropped.games)}** games.\n\n`;
  dq += `Both change the answer to this question. Two games — Jun 8, 1989 (PIT @ PHI) and `
     + `Aug 21, 1990 (PHI @ LAN) — are false positives created by a phantom run, and they drop out `
     + `once runs are derived. One game — Sep 4, 2002 (KCA @ OAK) — is a false negative: a dropped `
     + `run left the ninth-inning tie showing as 11–10, hiding a genuine blown 11-run lead.\n\n`;
  dq += `## What this study cannot see\n\n`;
  dq += `**${num(+cov.without_pbp)}** of the **${num(+cov.candidates)}** candidate games (both teams `
     + `11+ runs) have a game log but no play-by-play, so their trajectory is unknowable here — `
     + `${cov.earliest_gap} to ${cov.latest_gap}, overwhelmingly the pre-1900 game.\n\n`;
  dq += "| Decade | Candidates | Without play-by-play |\n| --- | --- | --- |\n";
  for (const r of covDecade) dq += `| ${r.decade}s | ${num(+r.candidates)} | ${num(+r.without_pbp)} |\n`;
  writeFileSync(join(DIR, "03-data-quality.md"), dq);

  // --- console summary -------------------------------------------------------
  console.log(`Blown 11+ run leads: ${games.length} (${lost.length} lost, ${games.length - lost.length} survived)`);
  for (const r of games) {
    console.log(`  ${r.game_date}  ${r.visitor_team} @ ${r.home_team}  led by ${r.lead}  `
      + `${r.visitor_score}-${r.home_score}${attended.has(r.game_id) ? "  <- attended" : ""}`
      + `${r.score_verified ? "" : "  !! final score does not match the game log"}`);
  }
  console.log(`10-run leads given up entirely: ${near.length}`);
  console.log("Wrote 01-blown-leads.md, 02-near-misses.md, 03-data-quality.md");
}

function ord(n: number) {
  const s = ["th", "st", "nd", "rd"][(n % 100 - 20) % 10] ?? ["th", "st", "nd", "rd"][n % 100] ?? "th";
  return `${n}${s}`;
}

await main();
