// Copyright (c) 2026 Syd Polk
// SPDX-License-Identifier: BSD-3-Clause
//
// HOF sightings: cross-reference Syd's attended-games log against the Retrosheet
// mart to find the first game he saw each Hall of Famer — as a player (from the
// lineups) OR as a manager (from game_log's manager of record). Flags box-score
// links that don't resolve, and regenerates the printable plaque checklist.
//
// Run (research default is Plex; override with DATABASE_URL):
//   tsx research/hof-sightings/run.ts
//   DATABASE_URL=postgres://retrosheet:retrosheet@localhost:5432/retrosheet tsx research/hof-sightings/run.ts
//
// Input : attended-games.tsv   (date <TAB> retrosheet box-score URL; one per game)
// Output: 01-hall-of-famers.md, bad-links.md, hall-of-famers.html  (all generated)
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { Pool } from "pg";

const DIR = dirname(fileURLToPath(import.meta.url));
const DB = process.env.DATABASE_URL ?? "postgres://retrosheet:retrosheet@plex:5432/retrosheet";
const MONTHS = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];
const fmt = (iso) => { const [y, m, d] = iso.split("-"); return `${MONTHS[+m - 1]} ${+d}, ${y}`; };
const roleBadge = (roles) => roles === "manager+player" ? "P·M" : roles === "manager" ? "M" : "P";

// The mart schema evolves; a research DB may be older than this script expects
// (e.g. Plex not yet redeployed). Probe rather than assume, so the study degrades
// gracefully instead of crashing on a missing table.
const tableExists = async (pool, qualified) =>
  (await pool.query(`SELECT to_regclass($1) IS NOT NULL AS ok`, [qualified])).rows[0].ok;
async function schemaVersion(pool) {
  if (!(await tableExists(pool, "retrosheet.schema_meta"))) return null;
  const r = await pool.query(`SELECT version FROM retrosheet.schema_meta LIMIT 1`);
  return r.rows[0]?.version ?? null;
}

function parse() {
  const rows = [];
  const nonRetrosheet = [];
  const seen = new Set();
  for (const line of readFileSync(join(DIR, "attended-games.tsv"), "utf8").split(/\r?\n/)) {
    if (!line.trim()) continue;
    const [rawDate, url = ""] = line.split("\t");
    const dm = /^(\d{1,2})\/(\d{1,2})\/(\d{4})$/.exec(rawDate.trim());
    const logged = dm ? `${dm[3]}-${dm[1].padStart(2, "0")}-${dm[2].padStart(2, "0")}` : "";
    const m = /boxesetc\/\d{4}\/B(\d\d)(\d\d)(\d)([A-Z]{3})(\d{4})\.htm/.exec(url);
    if (!m) { nonRetrosheet.push({ date: rawDate, url }); continue; }
    const [, MM, DD, N, HOM, YYYY] = m;
    const gameId = `${HOM}${YYYY}${MM}${DD}${N}`;
    if (seen.has(gameId)) continue;
    seen.add(gameId);
    rows.push({ logged, url, gameId, hom: HOM, n: N, yyyy: YYYY });
  }
  return { rows, nonRetrosheet };
}

async function main() {
  const { rows, nonRetrosheet } = parse();
  const ids = rows.map((r) => r.gameId);
  const dates = rows.map((r) => r.logged);
  const byId = new Map(rows.map((r) => [r.gameId, r]));
  const pool = new Pool({ connectionString: DB });

  // Schema-mismatch handling: managers come from game_log, which older mart
  // deployments don't have yet. If it's absent, run players-only and say so,
  // rather than throwing on a missing relation.
  const hasGameLog = await tableExists(pool, "retrosheet.game_log");
  const ver = await schemaVersion(pool);
  const verLabel = ver === null ? "unversioned" : `v${ver}`;
  const stamp = `<!-- generated by run.ts from ${DB.replace(/:[^:@/]*@/, ":***@")} (schema ${verLabel}) on ${new Date().toISOString().slice(0, 10)} -->\n`;
  if (!hasGameLog) {
    console.warn("WARNING: retrosheet.game_log not present in this database — managers omitted (players only).");
    console.warn("         Redeploy the mart (update-service.sh) to populate managers, then re-run.");
  }

  // Manager sightings depend on game_log; include those UNION branches only when
  // the table exists.
  const managerBranches = hasGameLog
    ? `       UNION ALL
       SELECT gd.game_id, gd.game_date, gl.visitor_manager_id, 'manager' FROM good gd JOIN retrosheet.game_log gl ON gl.game_id = gd.game_id
       UNION ALL
       SELECT gd.game_id, gd.game_date, gl.home_manager_id, 'manager'    FROM good gd JOIN retrosheet.game_log gl ON gl.game_id = gd.game_id`
    : "";

  const bad = await pool.query(
    `WITH att AS (SELECT * FROM unnest($1::text[], $2::date[]) AS t(game_id, logged_date))
     SELECT a.game_id, a.logged_date::text AS logged, g.game_date::text AS points_to
     FROM att a LEFT JOIN retrosheet.game g ON g.game_id = a.game_id
     WHERE g.game_id IS NULL OR g.game_date <> a.logged_date
     ORDER BY a.logged_date`,
    [ids, dates],
  );

  // First time each Hall of Famer was seen — as player (lineups) or manager (game_log).
  const hof = await pool.query(
    `WITH att AS (SELECT * FROM unnest($1::text[], $2::date[]) AS t(game_id, logged_date)),
     good AS (SELECT a.game_id, g.game_date FROM att a
              JOIN retrosheet.game g ON g.game_id = a.game_id AND g.game_date = a.logged_date),
     sightings AS (
       SELECT gd.game_id, gd.game_date, ls.player_id, 'player' AS role FROM good gd JOIN retrosheet.lineup_start ls ON ls.game_id = gd.game_id
       UNION ALL
       SELECT gd.game_id, gd.game_date, s.player_id, 'player'  FROM good gd JOIN retrosheet.substitution s  ON s.game_id  = gd.game_id
${managerBranches ? managerBranches + "\n" : ""}     ),
     hof AS (
       SELECT s.player_id, s.game_date, s.game_id, s.role
       FROM sightings s JOIN retrosheet.people p ON p.player_id = s.player_id
       WHERE p.hof = 'HOF' AND s.player_id IS NOT NULL),
     firsts AS (
       SELECT DISTINCT ON (player_id) player_id, game_date, game_id FROM hof
       ORDER BY player_id, game_date, game_id),
     roles AS (SELECT player_id, string_agg(DISTINCT role, '+' ORDER BY role) AS roles FROM hof GROUP BY player_id)
     SELECT coalesce(nullif(p.nickname, ''), p.first_name) || ' ' || p.last_name AS name,
            p.last_name, f.game_date::text AS first_seen, r.roles,
            g.visitor_team AS vis, g.home_team AS home
     FROM firsts f
     JOIN roles r USING (player_id)
     JOIN retrosheet.people p ON p.player_id = f.player_id
     JOIN retrosheet.game g ON g.game_id = f.game_id
     ORDER BY p.last_name, name`,
    [ids, dates],
  );
  await pool.end();

  // --- bad-links.md ----------------------------------------------------------
  let badMd = `${stamp}# Incorrect box-score links\n\n`;
  if (bad.rows.length === 0) {
    badMd += "None — every link resolves to a game on its logged date.\n";
  } else {
    badMd += "| Logged date | Link points to | Fix the URL to |\n| --- | --- | --- |\n";
    for (const b of bad.rows) {
      const r = byId.get(b.game_id);
      const [, m, d] = b.logged.split("-");
      const fix = r ? `.../B${m}${d}${r.n}${r.hom}${r.yyyy}.htm` : "(game not found)";
      badMd += `| ${b.logged} | ${b.points_to ?? "not found"} | \`${fix}\` |\n`;
    }
  }
  writeFileSync(join(DIR, "bad-links.md"), badMd);

  // --- 01-hall-of-famers.md --------------------------------------------------
  let md = `${stamp}# Hall of Famers seen, first sighting\n\n`;
  md += `**${hof.rows.length}** members (P = seen as player, M = as manager), alphabetical by last name.\n\n`;
  if (!hasGameLog) {
    md += "> _Managers omitted: this database predates the `game_log` table. " +
      "Redeploy the mart and re-run to include manager sightings._\n\n";
  }
  md += "| ✓ | Role | Hall of Famer | First saw | Game |\n| --- | --- | --- | --- | --- |\n";
  for (const r of hof.rows) md += `|  | ${roleBadge(r.roles)} | ${r.name} | ${fmt(r.first_seen)} | ${r.vis} @ ${r.home} |\n`;
  writeFileSync(join(DIR, "01-hall-of-famers.md"), md);

  // --- hall-of-famers.html (printable checklist) -----------------------------
  const trs = hof.rows
    .map((r) => `      <tr><td class="chk"></td><td class="role">${roleBadge(r.roles)}</td><td class="name">${r.name}</td><td class="date">${fmt(r.first_seen)}</td><td class="game">${r.vis} @ ${r.home}</td></tr>`)
    .join("\n");
  writeFileSync(join(DIR, "hall-of-famers.html"), htmlTemplate(hof.rows.length, trs));

  // --- console summary -------------------------------------------------------
  const managers = hof.rows.filter((r) => r.roles.includes("manager")).length;
  const players = hof.rows.filter((r) => r.roles.includes("player")).length;
  console.log(`Hall of Famers seen: ${hof.rows.length} (as player: ${players}, as manager: ${managers})`);
  console.log(`Bad links: ${bad.rows.length}`);
  for (const b of bad.rows) console.log(`  ${b.logged} -> link points to ${b.points_to ?? "(not found)"}`);
  if (nonRetrosheet.length) console.log(`Skipped ${nonRetrosheet.length} non-Retrosheet/unparseable link(s).`);
  console.log("Wrote 01-hall-of-famers.md, bad-links.md, hall-of-famers.html");
}

function htmlTemplate(count, trs) {
  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Hall of Famers I've Seen</title>
<style>
  :root { color-scheme: light; }
  * { box-sizing: border-box; }
  body { margin: 2rem auto; max-width: 42rem; padding: 0 1.25rem; background: #fff; color: #1a1a1a; font: 15px/1.5 Georgia, "Times New Roman", serif; }
  h1 { font-size: 1.5rem; margin: 0 0 .15rem; }
  .sub { font: 12px/1.4 system-ui, sans-serif; color: #555; letter-spacing: .02em; margin-bottom: 1.1rem; }
  table { width: 100%; border-collapse: collapse; }
  th, td { text-align: left; padding: .38rem .5rem; border-bottom: 1px solid #d8d8d8; }
  th { font: 11px/1 system-ui, sans-serif; text-transform: uppercase; letter-spacing: .06em; color: #666; border-bottom: 1.5px solid #999; }
  .chk { width: 2.2rem; border: 1px solid #bbb; }
  thead .chk { border: none; border-bottom: 1.5px solid #999; }
  .role { width: 2.5rem; font: 11px/1 system-ui, sans-serif; color: #666; letter-spacing: .04em; }
  .name { font-weight: 600; }
  .date, .game { font: 12px/1.4 system-ui, sans-serif; color: #444; font-variant-numeric: tabular-nums; white-space: nowrap; }
  tbody tr:nth-child(even) td:not(.chk) { background: #faf9f7; }
  @media print { body { margin: 0; max-width: none; font-size: 11pt; } tr { break-inside: avoid; } }
</style></head>
<body>
  <h1>Hall of Famers I've Seen</h1>
  <div class="sub">${count} members &middot; P = player, M = manager &middot; check off each plaque at Cooperstown</div>
  <table>
    <thead><tr><th class="chk">&#10003;</th><th class="role">Role</th><th>Hall of Famer</th><th>First saw</th><th>Game</th></tr></thead>
    <tbody>
${trs}
    </tbody>
  </table>
</body></html>
`;
}

main().catch((e) => { console.error(e); process.exit(1); });
